version: "3"

services:
  dynamodb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - contract-management-backend:/home/dynamodblocal/db

volumes:
  contract-management-backend:
    driver: local